CREATE TABLE PRODUCTO (
Id_Producto INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL,
Codigo_Barras VARCHAR(20) UNIQUE,
Precio_Venta DOUBLE NOT NULL,
foto LONGTEXT,
Id_Categoria INT NOT NULL,
Id_Uni_Med INT NOT NULL,
Id_Marca INT NOT NULL,
Estado INT NOT NULL);

CREATE TABLE MARCA (
Id_Marca INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Logo LONGTEXT,
Estado INT NOT NULL);

CREATE TABLE CLIENTE (
Id_Cliente INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30),
Apellido VARCHAR(30),
Telefono VARCHAR(9),
Foto VARCHAR(400),
Observaciones VARCHAR(400),
Id_Usuario INT);

CREATE TABLE DETALLE_VENTA (
Id_Producto INT NOT NULL,
Id_Venta INT NOT NULL,
Descuento DOUBLE,
Fecha DATETIME NOT NULL,
Estado INT NOT NULL,
PRIMARY KEY (Id_Producto,Id_Venta));

CREATE TABLE PERDIDA (
Id_Perdida INT AUTO_INCREMENT PRIMARY KEY,
Precio_Compra DOUBLE NOT NULL,
Cantidad INT NOT NULL,
Fecha DATETIME NOT NULL,
Id_Producto INT NOT NULL);

CREATE TABLE EMPLEADO (
Id_Bodeguero INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30),
Apellido VARCHAR(50),
Telefono VARCHAR(9),
Foto VARCHAR(400),
Id_Usuario INT NOT NULL);

CREATE TABLE USUARIO (
Id_Usuario INT AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(30) NOT NULL UNIQUE,
Password VARCHAR(300) NOT NULL,
Fecha_Creacion DATETIME NOT NULL,
Correo VARCHAR(255),
Estado INT NOT NULL);

CREATE TABLE ROL (
Id_Rol INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL);

CREATE TABLE VENTA (
Id_Venta INT AUTO_INCREMENT PRIMARY KEY,
Id_Cliente INT NOT NULL,
Descuento DOUBLE NOT NULL,
Fecha DATETIME NOT NULL);

CREATE TABLE COMPRA (
Id_Compra INT AUTO_INCREMENT PRIMARY KEY,
Fecha DATETIME NOT NULL);

CREATE TABLE DETALLE_COMPRA (
Id_Producto INT NOT NULL,
Id_Compra INT NOT NULL,
Precio DOUBLE NOT NULL,
Cantidad INT NOT NULL,
Descuento DOUBLE NOT NULL,
PRIMARY KEY (Id_Producto,Id_Compra));

CREATE TABLE UNIDAD_MEDIDA (
Id_Uni_Med INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(100) NOT NULL);

CREATE TABLE CATEGORIA (
Id_Categoria INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(150) NOT NULL);

CREATE TABLE RESERVA (
Id_Reserva INT AUTO_INCREMENT PRIMARY KEY,
Fec_Entrada DATETIME NOT NULL,
Fec_Salida DATETIME NOT NULL);

CREATE TABLE HABITACION (
Id_Hab INT AUTO_INCREMENT PRIMARY KEY,
Numero VARCHAR(4) NOT NULL);

CREATE TABLE DETALLE_RESERVA (
Id_Cliente INT NOT NULL,
Id_Reserva INT NOT NULL,
Id_Hab INT NOT NULL,
PRIMARY KEY (Id_Cliente,Id_Reserva));

CREATE TABLE ROL_USUARIO (
Id_Usuario INT NOT NULL,
Id_Rol INT NOT NULL,
PRIMARY KEY (Id_Usuario,Id_Rol));

ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_Id_Categoria_CATEGORIA_Id_Categoria FOREIGN KEY (Id_Categoria) REFERENCES CATEGORIA(Id_Categoria);
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_Id_Uni_Med_UNIDAD_MEDIDA_Id_Uni_Med FOREIGN KEY (Id_Uni_Med) REFERENCES UNIDAD_MEDIDA(Id_Uni_Med);
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_Id_Marca_MARCA_Id_Marca FOREIGN KEY (Id_Marca) REFERENCES MARCA(Id_Marca);
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_Id_Usuario_USUARIO_Id_Usuario FOREIGN KEY (Id_Usuario) REFERENCES USUARIO(Id_Usuario);
ALTER TABLE DETALLE_VENTA ADD CONSTRAINT DETALLE_VENTA_Id_Producto_PRODUCTO_Id_Producto FOREIGN KEY (Id_Producto) REFERENCES PRODUCTO(Id_Producto);
ALTER TABLE DETALLE_VENTA ADD CONSTRAINT DETALLE_VENTA_Id_Venta_VENTA_Id_Venta FOREIGN KEY (Id_Venta) REFERENCES VENTA(Id_Venta);
ALTER TABLE PERDIDA ADD CONSTRAINT PERDIDA_Id_Producto_PRODUCTO_Id_Producto FOREIGN KEY (Id_Producto) REFERENCES PRODUCTO(Id_Producto);
ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_Id_Usuario_USUARIO_Id_Usuario FOREIGN KEY (Id_Usuario) REFERENCES USUARIO(Id_Usuario);
ALTER TABLE VENTA ADD CONSTRAINT VENTA_Id_Cliente_CLIENTE_Id_Cliente FOREIGN KEY (Id_Cliente) REFERENCES CLIENTE(Id_Cliente);
ALTER TABLE DETALLE_COMPRA ADD CONSTRAINT DETALLE_COMPRA_Id_Producto_PRODUCTO_Id_Producto FOREIGN KEY (Id_Producto) REFERENCES PRODUCTO(Id_Producto);
ALTER TABLE DETALLE_COMPRA ADD CONSTRAINT DETALLE_COMPRA_Id_Compra_COMPRA_Id_Compra FOREIGN KEY (Id_Compra) REFERENCES COMPRA(Id_Compra);
ALTER TABLE DETALLE_RESERVA ADD CONSTRAINT DETALLE_RESERVA_Id_Cliente_CLIENTE_Id_Cliente FOREIGN KEY (Id_Cliente) REFERENCES CLIENTE(Id_Cliente);
ALTER TABLE DETALLE_RESERVA ADD CONSTRAINT DETALLE_RESERVA_Id_Reserva_RESERVA_Id_Reserva FOREIGN KEY (Id_Reserva) REFERENCES RESERVA(Id_Reserva);
ALTER TABLE DETALLE_RESERVA ADD CONSTRAINT DETALLE_RESERVA_Id_Hab_HABITACION_Id_Hab FOREIGN KEY (Id_Hab) REFERENCES HABITACION(Id_Hab);
ALTER TABLE ROLES_USUARIO ADD CONSTRAINT ROLES_USUARIO_Id_Usuario_USUARIO_Id_Usuario FOREIGN KEY (Id_Usuario) REFERENCES USUARIO(Id_Usuario);
ALTER TABLE ROLES_USUARIO ADD CONSTRAINT ROLES_USUARIO_Id_Rol_ROL_Id_Rol FOREIGN KEY (Id_Rol) REFERENCES ROL(Id_Rol);
